name: mama_meow
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.11+13
environment:
  sdk: ^3.9.0

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  flutter:
    sdk: flutter
  flutter_localizations: # Add this line for localizations
    sdk: flutter    

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^1.0.8
  lucide_icons: ^0.257.0

  get: ^4.6.6
  get_storage: ^2.1.1

  http: ^1.5.0
  http_parser: ^4.1.2
 

  purchases_flutter: ^9.6.1
  url_launcher: ^6.3.2

  intl: ^0.20.2
  crypto: ^3.0.6
  flutter_markdown: ^0.7.7+1
  cached_network_image: ^3.4.1
  flutter_svg: ^2.2.1
  syncfusion_flutter_charts: ^31.1.17

  just_audio: ^0.10.5
  image_picker: ^1.2.0
  flutter_image_compress: ^2.4.0
  

  record: ^6.1.1
  path_provider: ^2.1.5
  path: ^1.9.1

  firebase_core: ^4.0.0
  firebase_auth: ^6.0.2
  firebase_database: ^12.0.0
  firebase_analytics: ^12.0.4
  firebase_crashlytics: ^5.0.5
  firebase_storage: 13.0.1


  package_info_plus: ^9.0.0
  device_info_plus: ^12.3.0

  google_sign_in: ^6.3.0
  sign_in_with_apple: ^7.0.1
  googleapis_auth: ^2.0.0

  flutter_local_notifications: ^19.4.2
  timezone: ^0.10.1
  flutter_timezone: ^5.0.0

  flutter_launcher_icons: ^0.14.4


flutter_launcher_icons:
  #  image_path: "assets/images/icon-128x128.png"
  image_path_android: "assets/full-logo.png"
  image_path_ios: "assets/full-logo.png"
  android: true # can specify file name here e.g. "ic_launcher"
  ios: true # can specify file name here e.g. "My-Launcher-Icon"
  adaptive_icon_background: "assets/full-logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground: "assets/full-logo.png" # only available for Android 8.0 devices and above
  adaptive_icon_foreground_inset: 16 # only available for Android 8.0 devices and above
  adaptive_icon_monochrome: "assets/full-logo.png" # only available for Android 13 devices and above
  min_sdk_android: 21 # android min sdk min:16, default 21
  remove_alpha_ios: true
  background_color_ios: "#ffffff"
  


dev_dependencies:
  flutter_test:
    sdk: flutter



  # The "flutter_lints" package below contains a set of recommended lints to
  # encourage good coding practices. The lint set provided by the package is
  # activated in the `analysis_options.yaml` file located at the root of your
  # package. See that file for information about deactivating specific lint
  # rules and activating additional ones.
  flutter_lints: ^5.0.0

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/
    - assets/foods/
    - assets/fonts/
  #   - images/a_dot_ham.jpeg

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/to/resolution-aware-images

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/to/asset-from-package

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: Nunito
      fonts:
        - asset: assets/fonts/nunito/Nunito-Regular.ttf
        - asset: assets/fonts/nunito/Nunito-Bold.ttf
          weight: 700
        - asset: assets/fonts/nunito/Nunito-BoldItalic.ttf
          weight: 700
          style: italic
        - asset: assets/fonts/nunito/Nunito-Italic.ttf
          style: italic
        - asset: assets/fonts/nunito/Nunito-Black.ttf
          weight: 900
        - asset: assets/fonts/nunito/Nunito-BlackItalic.ttf
          weight: 900
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/nunito/Nunito-ExtraBoldItalic.ttf
          weight: 800
          style: italic
        - asset: assets/fonts/nunito/Nunito-ExtraLight.ttf
          weight: 200
        - asset: assets/fonts/nunito/Nunito-ExtraLightItalic.ttf
          weight: 200
          style: italic
        - asset: assets/fonts/nunito/Nunito-Light.ttf
          weight: 300
        - asset: assets/fonts/nunito/Nunito-LightItalic.ttf
          weight: 300
          style: italic
        - asset: assets/fonts/nunito/Nunito-Medium.ttf
          weight: 500
        - asset: assets/fonts/nunito/Nunito-MediumItalic.ttf
          weight: 500
          style: italic
        - asset: assets/fonts/nunito/Nunito-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/nunito/Nunito-SemiBoldItalic.ttf
          weight: 600
          style: italic
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/to/font-from-package
